# WEB SERVER
# https://www.ionos.com/digitalguide/websites/web-development/nodejs-for-a-website-with-apache-on-ubuntu/
- hosts: web
  become: true
  vars_files: vars/main.yml

  tasks:
  - name: install apache and nodejs last version
    apt:
      name:
        - apache2
        - nodejs
        - npm
        - build-essential
        - libapache2-mod-php
      state: present
      update_cache: yes

  # so that it will automatically restart if the server is rebooted
  - name: Use npm to install PM2
    command: npm install -g pm2

  - name: upgrade uuid
    command: npm install -g uuid@latest

  - name: Give writable mode to http folder
    file:
      path: /var/www/html/
      state: directory
      mode: '0755'

  - name: Give writable mode to nodejs folder
    file:
      path: /var/www/html/nodejs
      state: directory
      mode: '0755'

  # - name: remove default index.html
  #   file:
  #     path: /var/www/html/index.php
  #     state: absent

  # - name: upload web app source
  #   copy:
  #     src: app/
  #     dest: /var/www/html/

  # - name: deploy php database config
  #   template:
  #     src: "db-config.php.j2"
  #     dest: "/var/www/html/db-config.php"

  #===============for nodejs=========================
  - name: Enable the Apache2 module proxy
    community.general.apache2_module:
      state: present
      name: proxy

  - name: Enable the Apache2 module proxy_http
    community.general.apache2_module:
      state: present
      name: proxy_http

  # =========== proxy for nodejs =====================
  - name: Copy apache proxy config
    template:
      src: "templates/example.com.conf.j2"
      dest: "/etc/apache2/sites-available/example.com.conf"
  # ==================================================
  # - name: apache2 listen on port 8080
  #   lineinfile: dest=/etc/apache2/ports.conf regexp="^Listen 80" line="Listen 8080" state=present
  #   notify:
  #     - apache service restart

  # - name: "UFW firewall allow HTTP on port 80"
  #   ufw:
  #     rule: allow
  #     port: "80"
  #     proto: tcp

  - name: Enable site
    command: a2ensite example.com.conf


  # - name: apache2 virtualhost on port 8080
  #   lineinfile: dest=/etc/apache2/sites-available/000-default.conf regexp="^<VirtualHost \*:80>" line="<VirtualHost *:8080>" state=present
  #   notify:
  #     - restart apache2
  
  # - name: apache service restart
  #   service:
  #     name: apache2
  #     state: restarted
      
  - name: ensure apache service is start
    service:
      name: apache2
      state: started
      enabled: yes

  handlers:
    - name: restart apache2
      service: name=apache2 state=restarted