version: '3'
services:
  master:
    build:
      context: .
      dockerfile: ./master.Dockerfile
      #dockerfile: ../master.Dockerfile
    working_dir: /root/playbooks
    volumes:
      - ./ansible/playbooks:/root/playbooks
      - ./ansible/config:/etc/ansible
    command: tail -f /dev/null
    
  web:
    build:
      context: .
      dockerfile: ./server.Dockerfile

  db:
    environment:
      MYSQL_ROOT_HOST: '%'
    build:
      context: .
      dockerfile: ./server.Dockerfile

  lb:
    build:
      context: .
      dockerfile: ./server.Dockerfile
    ports: 
    - 5000:5000